project:
  id: 2025-10-15-exp003
  root_dir: "./output"
  description: "测试新的config文件"

task:
  mode: "capture_measurement"     # 可选: calibration | capture_psf | capture_measurement
  repeat: 1               # 拍摄次数
  description: "尝试capture_measurement任务"

capture_settings:
  exposure_us: 581046.0000
  monitor_idx: 2
  scale_factor: 0.27
  display_position: (0,0)   # 功能需要在代码里面修改以启用
  display_image_path: "D:/qjy/camera_slm_pipeline/data/example/分辨率测试卡.jpg"
  slm_image_path: "D:/qjy/camera_slm_pipeline/data/fza_bin_gen/FZA_bin_R25.png"

physical_setup:
  object_name: "打印的实物分辨率卡*2"
  brightness: "LED-4045"
  sensor_mask_distance: ""
  mask_object_distance1: "15cm"
  mask_object_distance2: "37.5cm"
  point_light_brightness: 4045
  mask_LED-light_distance: ""
  